version: '3.8'

services:
  server:
    container_name: area_server
    build: ./backend
    env_file: .env
    ports:
      - "8080:3000"
    networks:
      - backend_network

  client_web:
    container_name: area_web
    build: ./frontend/web
    ports:
      - "8081:3000"

  database:
    image: postgres:16-alpine
    restart: always
    ports:
      - "5432:5432"
    env_file: .env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE}
    volumes:
      - database_volume:/var/lib/postgresql/data
    networks:
      - backend_network

volumes:
  database_volume:

networks:
  backend_network:
