version: '3.9'

services:
  database:
    container_name: area_database_dev
    image: postgres:16.0-alpine3.18
    restart: always
    env_file: backend/back/.env
    ports:
      - "5432:5432"
    volumes:
      - database_dev_volume:/var/lib/postgresql/data

volumes:
  database_dev_volume:
