version: '3.9'

services:
  client_mobile:
    container_name: area_mobile
    build: ./frontend/mobile
    volumes:
      - apk_volume:/app/build/app/outputs/apk/release

  client_web:
    container_name: area_web
    build: ./frontend/web
    ports:
      - "8081:3000"
    volumes:
      - apk_volume:/app/apk/
    networks:
      - web_network
      - nginx_web_network
    depends_on:
      - client_mobile
      - server

  server:
    container_name: area_server
    build: ./backend/back
    env_file: backend/back/.env
    ports:
      - "8080:3000"
      - "50050:50050"
    networks:
      - backend_network
      - web_network
      - nginx_server_network
    depends_on:
      - database

  database:
    container_name: area_database
    image: postgres:16.0-alpine3.18
    restart: always
    env_file: backend/back/.env
    ports:
      - "5432:5432"
    volumes:
      - database_volume:/var/lib/postgresql/data
    networks:
      - backend_network

  nginx:
    image: nginx:latest
    container_name: area_nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/area.conf:/etc/nginx/conf.d/default.conf:ro
      - /etc/letsencrypt/archive/area.rezar.fr:/etc/nginx/ssl/area.rezar.fr:ro
      - /etc/letsencrypt/archive/api.area.rezar.fr:/etc/nginx/ssl/api.area.rezar.fr:ro
    networks:
      - nginx_web_network
      - nginx_server_network
    depends_on:
      - client_web
      - server
    profiles:
      - prod

volumes:
  database_volume:
  apk_volume:

networks:
  backend_network:
  web_network:
  nginx_web_network:
  nginx_server_network:
