parser: "@typescript-eslint/parser"

parserOptions:
  ecmaVersion: latest
  project: tsconfig.json

extends:
  - airbnb-base
  - airbnb-typescript
  - plugin:@typescript-eslint/recommended
  - plugin:@next/next/recommended
  - prettier

rules:
  no-plusplus: [ "error", { "allowForLoopAfterthoughts": true } ]
  no-console: [ "error", { allow: [ "error" ] } ]
  "import/extensions": [ "error", "ignorePackages", { "": "never", } ]

  react/jsx-filename-extension: off
