version: '3.8'

services:
  supervisor:
    container_name: area_supervisor
    build: .
    env_file: .env
    ports:
      - "50051:50051"

  seconds-interval:
    container_name: seconds-interval
    build: ../workers/seconds-interval
