version: '3.8'

services:
  supervisor:
    container_name: area_supervisor
    build: .
    env_file: .env
    ports:
      - "${GRPC_SERVER_PORT}:${GRPC_SERVER_PORT}"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  seconds-interval:
    container_name: seconds-interval
    build: ../workers/seconds-interval

  google:
    container_name: google
    build:
      context: ../workers/google
      args:
        - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
        - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
        - GOOGLE_TOKEN_URI=${GOOGLE_TOKEN_URI}
