version: '3.8'

services:
  supervisor:
    container_name: area_supervisor
    build: .
    env_file: .env
    ports:
      - "${GRPC_SERVER_PORT}:${GRPC_SERVER_PORT}"

  seconds-interval:
    container_name: seconds-interval
    build: ../workers/seconds-interval

  gmail:
    container_name: gmail
    build: ../workers/gmail
    env_file: ../workers/gmail/.env
