version: '3.8'

services:
  supervisor:
    container_name: area_supervisor
    build: .
    env_file: .env
    ports:
      - "${GRPC_SERVER_PORT}:${GRPC_SERVER_PORT}"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  github:
    container_name: github
    build:
      context: ../workers/github
      args:
        - GITHUB_WEBHOOK_URL=${GITHUB_WEBHOOK_URL}
        - GITHUB_WEBHOOK_SECRET=${GITHUB_WEBHOOK_SECRET}

  gitlab:
    container_name: gitlab
    build:
      context: ../workers/gitlab
      args:
        - GITLAB_WEBHOOK_URL=${GITLAB_WEBHOOK_URL}
        - GITLAB_WEBHOOK_SECRET=${GITLAB_WEBHOOK_SECRET}

  google:
    container_name: google
    build:
      context: ../workers/google
      args:
        - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
        - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
        - GOOGLE_TOKEN_URI=${GOOGLE_TOKEN_URI}

  linear:
    container_name: linear
    build:
      context: ../workers/linear

  linkedin:
    container_name: linkedin
    build:
      context: ../workers/linkedin

  seconds-interval:
    container_name: seconds-interval
    build: ../workers/seconds-interval
