env:
  browser: true
  es2022: true

extends:
  - airbnb-base
  - airbnb-typescript/base
  - plugin:@typescript-eslint/recommended
  - prettier

parser: '@typescript-eslint/parser'

parserOptions:
  project: tsconfig.json
  ecmaVersion: latest
  sourceType: module

rules:
  no-plusplus: ["error", { "allowForLoopAfterthoughts": true }]
  no-console: off
  "@typescript-eslint/no-non-null-assertion": off