import 'package:flutter/material.dart';
import 'package:flutter_gen/gen_l10n/app_localizations.dart';

String getLocalizedString(String key, BuildContext context) {
  switch (key) {
    case "on_new_video":
      return AppLocalizations.of(context)!.on_new_video;
    case "on_new_video_sub":
      return AppLocalizations.of(context)!.on_new_video_sub;
    case "create_draft_email":
      return AppLocalizations.of(context)!.create_draft_email;
    case "update_signature_email":
      return AppLocalizations.of(context)!.update_signature_email;
    case "create_comment_youtube":
      return AppLocalizations.of(context)!.create_comment_youtube;
    case "create_document_docs":
      return AppLocalizations.of(context)!.create_document_docs;
    case "create_presentation":
      return AppLocalizations.of(context)!.create_presentation;
    case "create_spreadsheet":
      return AppLocalizations.of(context)!.create_spreadsheet;
    case "create_form":
      return AppLocalizations.of(context)!.create_form;
    case "create_contact":
      return AppLocalizations.of(context)!.create_contact;
    case "create_task_list":
      return AppLocalizations.of(context)!.create_task_list;
    case "create_course":
      return AppLocalizations.of(context)!.create_course;
    case "create_calendar":
      return AppLocalizations.of(context)!.create_calendar;
    case "create_drive_folder":
      return AppLocalizations.of(context)!.create_drive_folder;
    case "duplicate_drive_file":
      return AppLocalizations.of(context)!.duplicate_drive_file;
    case "form_add_youtube_item":
      return AppLocalizations.of(context)!.form_add_youtube_item;
    case "create_slide_on_presentation":
      return AppLocalizations.of(context)!.create_slide_on_presentation;
    case "create_shared_drive":
      return AppLocalizations.of(context)!.create_shared_drive;
    case "change_gmail_interface_language":
      return AppLocalizations.of(context)!.change_gmail_interface_language;
    case "form_update_description":
      return AppLocalizations.of(context)!.form_update_description;
    case "form_convert_to_quiz":
      return AppLocalizations.of(context)!.form_convert_to_quiz;
    case "update_spreadsheet_title":
      return AppLocalizations.of(context)!.update_spreadsheet_title;
    case "create_draft_email_sub":
      return AppLocalizations.of(context)!.create_draft_email_sub;
    case "update_signature_email_sub":
      return AppLocalizations.of(context)!.update_signature_email_sub;
    case "create_comment_youtube_sub":
      return AppLocalizations.of(context)!.create_comment_youtube_sub;
    case "create_document_docs_sub":
      return AppLocalizations.of(context)!.create_document_docs_sub;
    case "create_presentation_sub":
      return AppLocalizations.of(context)!.create_presentation_sub;
    case "create_spreadsheet_sub":
      return AppLocalizations.of(context)!.create_spreadsheet_sub;
    case "create_form_sub":
      return AppLocalizations.of(context)!.create_form_sub;
    case "create_contact_sub":
      return AppLocalizations.of(context)!.create_contact_sub;
    case "create_task_list_sub":
      return AppLocalizations.of(context)!.create_task_list_sub;
    case "create_course_sub":
      return AppLocalizations.of(context)!.create_course_sub;
    case "create_calendar_sub":
      return AppLocalizations.of(context)!.create_calendar_sub;
    case "create_drive_folder_sub":
      return AppLocalizations.of(context)!.create_drive_folder_sub;
    case "duplicate_drive_file_sub":
      return AppLocalizations.of(context)!.duplicate_drive_file_sub;
    case "form_add_youtube_item_sub":
      return AppLocalizations.of(context)!.form_add_youtube_item_sub;
    case "create_slide_on_presentation_sub":
      return AppLocalizations.of(context)!.create_slide_on_presentation_sub;
    case "create_shared_drive_sub":
      return AppLocalizations.of(context)!.create_shared_drive_sub;
    case "change_gmail_interface_language_sub":
      return AppLocalizations.of(context)!.change_gmail_interface_language_sub;
    case "form_update_description_sub":
      return AppLocalizations.of(context)!.form_update_description_sub;
    case "form_convert_to_quiz_sub":
      return AppLocalizations.of(context)!.form_convert_to_quiz_sub;
    case "update_spreadsheet_title_sub":
      return AppLocalizations.of(context)!.update_spreadsheet_title_sub;
    case "create_post":
      return AppLocalizations.of(context)!.create_post;
    case "create_post_sub":
      return AppLocalizations.of(context)!.create_post_sub;
    case "on_issue_reopen":
      return AppLocalizations.of(context)!.on_issue_reopen;
    case "on_issue_reopen_sub":
      return AppLocalizations.of(context)!.on_issue_reopen_sub;
    case "on_issue_close":
      return AppLocalizations.of(context)!.on_issue_close;
    case "on_issue_close_sub":
      return AppLocalizations.of(context)!.on_issue_close_sub;
    case "create_issue":
      return AppLocalizations.of(context)!.create_issue;
    case "create_issue_sub":
      return AppLocalizations.of(context)!.create_issue_sub;
    case "reopen_issue":
      return AppLocalizations.of(context)!.reopen_issue;
    case "reopen_issue_sub":
      return AppLocalizations.of(context)!.reopen_issue_sub;
    case "close_issue":
      return AppLocalizations.of(context)!.close_issue;
    case "close_issue_sub":
      return AppLocalizations.of(context)!.close_issue_sub;
    case "seconds_interval":
      return AppLocalizations.of(context)!.seconds_interval;
    case "seconds_interval_sub":
      return AppLocalizations.of(context)!.seconds_interval_sub;
    case "on_issue_create":
      return AppLocalizations.of(context)!.on_issue_create;
    case "on_issue_create_sub":
      return AppLocalizations.of(context)!.on_issue_create_sub;
    case "on_commit":
      return AppLocalizations.of(context)!.on_commit;
    case "on_commit_sub":
      return AppLocalizations.of(context)!.on_commit_sub;
    case "on_pull_request_close":
      return AppLocalizations.of(context)!.on_pull_request_close;
    case "on_pull_request_close_sub":
      return AppLocalizations.of(context)!.on_pull_request_close_sub;
    case "on_pull_request_create":
      return AppLocalizations.of(context)!.on_pull_request_create;
    case "on_pull_request_create_sub":
      return AppLocalizations.of(context)!.on_pull_request_create_sub;
    case "on_pull_request_merge":
      return AppLocalizations.of(context)!.on_pull_request_merge;
    case "on_pull_request_merge_sub":
      return AppLocalizations.of(context)!.on_pull_request_merge_sub;
    case "on_pull_request_reopen":
      return AppLocalizations.of(context)!.on_pull_request_reopen;
    case "on_pull_request_reopen_sub":
      return AppLocalizations.of(context)!.on_pull_request_reopen_sub;
    case "on_status_create":
      return AppLocalizations.of(context)!.on_status_create;
    case "on_status_create_sub":
      return AppLocalizations.of(context)!.on_status_create_sub;
    case "create_board":
      return AppLocalizations.of(context)!.create_board;
    case "create_board_sub":
      return AppLocalizations.of(context)!.create_board_sub;
    case "lol_on_game_end":
      return AppLocalizations.of(context)!.lol_on_game_end;
    case "lol_on_game_end_sub":
      return AppLocalizations.of(context)!.lol_on_game_end_sub;
    case "lol_on_game_loss":
      return AppLocalizations.of(context)!.lol_on_game_loss;
    case "lol_on_game_loss_sub":
      return AppLocalizations.of(context)!.lol_on_game_loss_sub;
    case "lol_on_game_win":
      return AppLocalizations.of(context)!.lol_on_game_win;
    case "lol_on_game_win_sub":
      return AppLocalizations.of(context)!.lol_on_game_win_sub;
    case "lol_on_level_up":
      return AppLocalizations.of(context)!.lol_on_level_up;
    case "lol_on_level_up_sub":
      return AppLocalizations.of(context)!.lol_on_level_up_sub;
    case "create_task":
      return AppLocalizations.of(context)!.create_task;
    case "create_task_sub":
      return AppLocalizations.of(context)!.create_task_sub;
    case "reopen_task":
      return AppLocalizations.of(context)!.reopen_task;
    case "reopen_task_sub":
      return AppLocalizations.of(context)!.reopen_task_sub;
    case "close_task":
      return AppLocalizations.of(context)!.close_task;
    case "close_task_sub":
      return AppLocalizations.of(context)!.close_task_sub;
    case "update_task":
      return AppLocalizations.of(context)!.update_task;
    case "update_task_sub":
      return AppLocalizations.of(context)!.update_task_sub;
    case "delete_task":
      return AppLocalizations.of(context)!.delete_task;
    case "delete_task_sub":
      return AppLocalizations.of(context)!.delete_task_sub;
    case "delete_record":
      return AppLocalizations.of(context)!.delete_record;
    case "delete_record_sub":
      return AppLocalizations.of(context)!.delete_record_sub;
    case "create_tweet":
      return AppLocalizations.of(context)!.create_tweet;
    case "create_tweet_sub":
      return AppLocalizations.of(context)!.create_tweet_sub;
    case "send_email":
      return AppLocalizations.of(context)!.send_email;
    case "send_email_sub":
      return AppLocalizations.of(context)!.send_email_sub;
    case "create_message":
      return AppLocalizations.of(context)!.create_message;
    case "create_message_sub":
      return AppLocalizations.of(context)!.create_message_sub;
    case "on_guild_join":
      return AppLocalizations.of(context)!.on_guild_join;
    case "on_guild_join_sub":
      return AppLocalizations.of(context)!.on_guild_join_sub;
    case "on_action":
      return AppLocalizations.of(context)!.on_action;
    case "on_action_sub":
      return AppLocalizations.of(context)!.on_action_sub;
    case "on_account_connect":
      return AppLocalizations.of(context)!.on_account_connect;
    case "on_account_connect_sub":
      return AppLocalizations.of(context)!.on_account_connect_sub;
    case "on_workflow_create":
      return AppLocalizations.of(context)!.on_workflow_create;
    case "on_workflow_create_sub":
      return AppLocalizations.of(context)!.on_workflow_create_sub;
    case "on_workflow_toggle":
      return AppLocalizations.of(context)!.on_workflow_toggle;
    case "on_workflow_toggle_sub":
      return AppLocalizations.of(context)!.on_workflow_toggle_sub;
    case "disable_workflow":
      return AppLocalizations.of(context)!.disable_workflow;
    case "disable_workflow_sub":
      return AppLocalizations.of(context)!.disable_workflow_sub;
    case "enable_workflow":
      return AppLocalizations.of(context)!.enable_workflow;
    case "enable_workflow_sub":
      return AppLocalizations.of(context)!.enable_workflow_sub;
  }
  return "";
}