name: Main workflow

on: [ push ]

env:
  MIRROR_URL: "git@github.com:EpitechPromo2026/B-DEV-500-PAR-5-1-area-reza.rahemtola.git"

jobs:
  eslint-backend:
    name: "ESLint: Backend"
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend/back
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: yarn
          cache-dependency-path: "backend/back/yarn.lock"
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Run eslint
        run: yarn lint > eslint-results
      - name: Get eslint results
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: eslint-back-results
          path: backend/back/eslint-results
          retention-days: 5

  eslint-web:
    name: "ESLint: Web"
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend/web/
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: yarn
          cache-dependency-path: "frontend/web/yarn.lock"
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Run eslint
        run: yarn lint > eslint-results
      - name: Get eslint results
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: eslint-web-results
          path: frontend/web/eslint-results
          retention-days: 5

  check-mobile:
    name: "Mobile: Analyze code & run tests"
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend/mobile/
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "17"
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.13.4"
          channel: stable
          cache: true
      - name: Check formatting
        run: dart format --set-exit-if-changed .
      - name: Analyze code
        run: flutter analyze
      - name: Run tests
        run: flutter test

  push-to-mirror:
    name: Push to Epitech repository
    runs-on: ubuntu-latest
    steps:
      - name: Repository checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Cloning to mirror
        uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url:
            ${{ env.MIRROR_URL }}
          ssh_private_key:
            ${{ secrets.GIT_SSH_PRIVATE_KEY }}
    needs:
      - eslint-backend
      - eslint-web
      - check-mobile
