name: Main workflow

on: [ push ]

env:
  MIRROR_URL: "git@github.com:EpitechPromo2026/B-DEV-500-PAR-5-1-area-reza.rahemtola.git"

jobs:
  build-supervisor:
    name: "Build: Supervisor"
    runs-on: self-hosted
    defaults:
      run:
        working-directory: ./backend/supervisor/
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup go
        uses: actions/setup-go@v4
        with:
          go-version-file: "backend/supervisor/go.mod"
          cache-dependency-path: "backend/supervisor/go.sum"
      - name: Install dependencies
        run: go mod download
      - name: Install protobuf & protoc-gen-go
        run: |
          sudo apt-get install -y protobuf-compiler
          go install google.golang.org/protobuf/cmd/protoc-gen-go@v1.27.1
          go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@v1.1.0
      - name: Fetch protobuf files
        run: git clone https://github.com/RezaRahemtola/area-proto.git proto
      - name: Generate protobuf go files
        run: protoc --experimental_allow_proto3_optional --go_out=proto --go_opt=paths=source_relative --go-grpc_out=proto --go-grpc_opt=paths=source_relative --proto_path=proto proto/area_supervisor.proto proto/area_types.proto
      - name: Run build
        run: go build

  eslint-backend:
    name: "ESLint: Backend"
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend/back/
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: yarn
          cache-dependency-path: "backend/back/yarn.lock"
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Run eslint
        run: yarn lint > eslint-results
      - name: Get eslint results
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: eslint-back-results
          path: backend/back/eslint-results
          retention-days: 5

  unit-tests-backend:
    name: "Unit tests: Backend"
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend/back/
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: yarn
          cache-dependency-path: "backend/back/yarn.lock"
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Run unit tests
        run: yarn test > unit-tests-results
      - name: Get unit tests results
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: unit-tests-back-results
          path: backend/back/unit-tests-results
          retention-days: 5

  eslint-web:
    name: "ESLint: Web"
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend/web/
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: yarn
          cache-dependency-path: "frontend/web/yarn.lock"
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Run eslint
        run: yarn lint > eslint-results
      - name: Get eslint results
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: eslint-web-results
          path: frontend/web/eslint-results
          retention-days: 5

  check-mobile:
    name: "Mobile: Analyze code & run tests"
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend/mobile/
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "17"
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.13.4"
          channel: stable
          cache: true
      - name: Create dummy env file
        run: touch .env
      - name: Check formatting
        run: dart format --set-exit-if-changed .
      - name: Analyze code
        run: flutter analyze
      - name: Run tests
        run: flutter test

  push-to-mirror:
    name: Push to Epitech repository
    runs-on: ubuntu-latest
    environment: Epitech repository
    steps:
      - name: Repository checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Cloning to mirror
        uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url:
            ${{ env.MIRROR_URL }}
          ssh_private_key:
            ${{ secrets.SSH_KEY }}
    needs:
      - build-supervisor
      - eslint-backend
      - unit-tests-backend
      - eslint-web
      - check-mobile
